sentences = [
    "Python is a popular programming language.",
    "FastAPI is used for building APIs.",
    "Machine learning helps computers learn from data.",
    "Artificial intelligence is transforming industries.",
    "Cats are independent animals.",
    "Dogs are loyal companions.",
    "Football is one of the world's most popular sports.",
    "Basketball requires teamwork.",
    "Cricket is widely played in India.",
    "Space exploration expands human knowledge.",
    "The Earth revolves around the Sun.",
    "Mars is called the Red Planet.",
    "The Moon influences ocean tides.",
    "Data science combines statistics and programming.",
    "Neural networks power modern AI.",
    "Large language models generate text.",
    "Vector embeddings represent text numerically.",
    "Semantic search understands meaning.",
    "Cosine similarity compares vectors.",
    "NumPy is useful for numerical computing.",
    "Pandas is used for data analysis.",
    "Git tracks code changes.",
    "GitHub hosts software repositories.",
    "Docker packages applications.",
    "Kubernetes manages containers.",
    "Cybersecurity protects digital systems.",
    "Encryption secures communication.",
    "Cloud computing offers scalable resources.",
    "AWS provides cloud services.",
    "Google Cloud hosts AI services.",
    "Azure is Microsoft's cloud platform.",
    "Reading books improves knowledge.",
    "Exercise keeps the body healthy.",
    "Meditation improves concentration.",
    "Coffee helps many people stay awake.",
    "Tea is enjoyed around the world.",
    "Travel broadens perspectives.",
    "Music can reduce stress.",
    "Photography captures memories.",
    "Programming requires logical thinking.",
    "Algorithms solve computational problems.",
    "Databases store structured information.",
    "SQL is used to query databases.",
    "APIs allow applications to communicate.",
    "JSON is a lightweight data format.",
    "Linux powers many servers.",
    "Windows is a popular operating system.",
    "MacOS is developed by Apple.",
    "Electric vehicles reduce emissions.",
    "Renewable energy supports sustainability."
]